### PR TITLE
Allow tags to be applied to Feature

### PR DESCRIPTION
**Pull request by JonathanTron**

### CODE REVIEW

**Comment by josepjaume** [comment]
Do you know if cucumber is also accepting tags on features?

Either way, sounds reasonable to me.

Thanks again! :heart:

**Comment by JonathanTron** [comment]
Yes, Cucumber accepts tags on feature for as long as I can remember (and I'm using it since it was still RSpec Story Runner).

**Comment by josepjaume** [comment]
Merging it then! :)

**Comment by JonathanTron** [comment]
Thanks, I forgot to remove the `START`  token I used when playing with the parser, I'm sending another pull-request for it.

**Pull request merged**
